#!/usr/bin/env bash
# Displays 'to infinity and beyond' indefinitely with 'sleep 2' in each iteration
# 'I am invicible!!!' when receiving SIGTERM signal

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invicible!!!"' SIGTERM
done
