#!/usr/bin/env bash
# This script shows the content of file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
