#!/usr/bin/env bash
# This script display the content of the current directory in list format
# Only display the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
